### ISSUE TITLE
release for Coq 8.11 ?

### ISSUE THREAD

**Issue by erikmd** [coq-community/coqoban#1]
Dear @herbelin,

I'd be very interested to have a coq-8.11 compatible opam package of coq-coqoban (given that the Coq version installed in our university workstations is 8.11.0 and that I'd like to use it for an assignement that will take place in 10 days :)

I've just checked the latest commit 89758d9bf1222155a37171e39ea1d6eec53aabb8 and it does compiles with Coq 8.11.0, but it seems from the git-tag naming convention of this repo that a tag `v8.11.0` will be necessary?

(I Cc @Zimmi48 as well just to let him know, as I briefly talked about this with him last week but he's not a watcher of the repo)

**Comment by Zimmi48** [comment]
@erikmd Let me suggest again that you take over the maintenance for this package as part of coq-community. This should be reasonably lightweight and allow you to do new releases whenever you need. If you are OK with this idea, let's open an issue in the manifesto repo so that other people know about it.

**Comment by erikmd** [comment]
OK @Zimmi48, let's do that :)

**Comment by herbelin** [comment]
@erikmd: Then, not doing anything on my side.

**Comment by erikmd** [comment]
Thanks Théo and Hugo, so let's say we'll close that issue when coq-coqoban.8.11.0 will be on opam (but first I'll open another PR regarding CI / README documentation)

**Comment by erikmd** [comment]
closing now - cf. https://github.com/coq/opam-coq-archive/pull/1192
